/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:800eff18-892c-466a-ad14-60828df74f4a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JRgafixTF",
    "aws_user_pools_web_client_id": "7don087jfdp58cpd59h6mr9th8",
    "oauth": {}
};


export default awsmobile;
